name: Vexor
url: https://vexor.io
markdown: redcarpet
highlighter: true
host: 0.0.0.0

exclude: [translate/, Rakefile, Gemfile, Gemfile.lock, vexor.yml, docker-compose.yml, _site/, .sass-cache/, .idea/]

help:
  - title: Configuration
    url: "/help/"
  - title: Ruby
    url: /help/ruby.html
  - title: Python
    url: /help/python.html
  - title: Scala
    url: /help/scala.html
  - title: Clojure
    url: /help/clojure.html
  - title: Node.js
    url: /help/nodejs.html
  - title: Go
    url: /help/go.html
  - title: Rust
    url: /help/rust.html
  - title: Services
    url: /help/services.html
  - title: Deploy
    url: /help/deploy.html

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      js: false

jekyll-press:
  exclude: 'sitemap.xml'

assets:
  autowrite: true
  cdn: https://cdn.example.com
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  assets:
    - "*.png"
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
