name: Vexor
url: https://vexor.io
markdown: redcarpet
highlighter: true

exclude: [translate/, Rakefile, Gemfile, Gemfile.lock, vexor.yml]

help:
  - title: Configuration
    url: "/help/"
  - title: Ruby
    url: /help/ruby.html
  - title: Python
    url: /help/python.html
  - title: Scala
    url: /help/scala.html
  - title: Clojure
    url: /help/clojure.html
  - title: Node.js
    url: /help/nodejs.html
  - title: Go
    url: /help/go.html
  - title: Rust
    url: /help/rust.html
  - title: Services
    url: /help/services.html
  - title: Deploy
    url: /help/deploy.html

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      js: false
