name: Vexor
url: https://vexor.io
markdown: redcarpet
highlighter: true

help:
  - title: Configuration
    url: /help
  - title: Ruby
    url: /help/ruby.html
  - title: Scala
    url: /help/scala.html
  - title: Clojure
    url: /help/clojure.html
  - title: Services
    url: /help/services.html
  - title: Node.js
    url: /help/nodejs.html
  - title: Go
    url: /help/go.html
  - title: Deploy
    url: /help/deploy.html

defaults:
  - scope:
      path: ""
      type: "page"
    values:
      js: false
